package Mk3::AppServer::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
  schema_class => 'Mk3::AppServer::Schema',
);

=head1 NAME

Mk3::AppServer::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Mk3::AppServer>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Mk3::AppServer::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Tom Bloor

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
